version: "3.5"

networks:
  narrative:
    name: traefik_narrative

services:
  traefik:
    image: "traefik:v2.1.1"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--metrics=true"
      - "--metrics.prometheus=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - narrative

  authsvc:
    image: "kbase/narrative-traefiker:latest"
    hostname: "authsvc"
    volumes:
      - "./app.py:/app/app.py"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "5000:5000"
    environment:
       - hostname=localhost
       - dock_net=traefik_narrative
    labels:
      - traefik.enable=true
      - traefik.http.routers.authsvc.rule=Host("localhost") && PathPrefix("/narrative")
      - traefik.http.routers.authsvc.entrypoints=web
    networks:
      - narrative

